export const GETALLARTICLS = "GETALLARTICLS";
export const ADDNEWARTICLE = "ADDNEWARTICLE";
export const GETCLICKEDARTICLE = "GETCLICKEDARTICLE";
export const DELETEONEARTICLE = "DELETEONEARTICLE";
export const UPDATEONEARTICLE = "UPDATEONEARTICLE";
